version: "3"
services:
  cache:
    image: redis:7-alpine
    volumes:
      - ./cache/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: unless-stopped

  directus:
    build:
      context: extensions
    depends_on:
      - cache
    environment:
      # general
      - PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
      # database
      - DB_CLIENT=pg
      - DB_CONNECTION_STRING
      # security
      - KEY=${DIRECTUS_KEY}
      - SECRET=${DIRECTUS_SECRET}
      - REFRESH_TOKEN_TTL=1d
      - REFRESH_TOKEN_COOKIE_SECURE=true
      - REFRESH_TOKEN_COOKIE_SAME_SITE=strict
      - REFRESH_TOKEN_COOKIE_NAME=geodashboard_refresh_token
      - PASSWORD_RESET_URL_ALLOW_LIST=${DIRECTUS_PASSWORD_RESET_URL_ALLOW_LIST}
      # cors
      - CORS_ENABLED=true
      - CORS_ORIGIN=true
      # redis
      - REDIS=redis://cache:6379
      # rate limiting
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_STORE=redis
      # cache
      - CACHE_ENABLED=true
      - CACHE_STORE=redis
      - CACHE_AUTO_PURGE=true
      - CACHE_SYSTEM_TTL=5m
      - CACHE_SKIP_ALLOWED=true
      # file storage
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY
      - STORAGE_S3_SECRET
      - STORAGE_S3_BUCKET
      - STORAGE_S3_ENDPOINT
      - STORAGE_S3_REGION
      - STORAGE_S3_ROOT
      # telemetry
      - TELEMETRY=false
      # email
      - EMAIL_TRANSPORT=ses
      - EMAIL_FROM
      - EMAIL_SES_CREDENTIALS__ACCESS_KEY_ID=${STORAGE_S3_KEY}
      - EMAIL_SES_CREDENTIALS__SECRET_ACCESS_KEY=${STORAGE_S3_SECRET}
      - EMAIL_SES_REGION=${STORAGE_S3_REGION}
      # scaling
      - SYNCHRONIZATION_STORE=redis
      - PM2_INSTANCES
      - PM2_AUTO_RESTART
      # initial acc
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - ADMIN_TOKEN
        # SSO
      - AUTH_PROVIDERS=ugems
      - AUTH_UGEMS_ALLOW_PUBLIC_REGISTRATION=true
      - AUTH_UGEMS_CLIENT_ID=${AUTH_UGEMS_CLIENT_ID}
      - AUTH_UGEMS_CLIENT_SECRET=${AUTH_UGEMS_CLIENT_SECRET}
      - AUTH_UGEMS_DEFAULT_ROLE_ID=${AUTH_UGEMS_DEFAULT_ROLE_ID}
      - AUTH_UGEMS_DRIVER=openid
      - AUTH_UGEMS_ICON=google
      - AUTH_UGEMS_IDENTIFIER_KEY=email
      - AUTH_UGEMS_ISSUER_URL=${AUTH_UGEMS_ISSUER_URL}
      - AUTH_UGEMS_LABEL=Ugems
      - AUTH_UGEMS_MODE=session
    deploy:
      replicas: ${DIRECTUS_REPLICAS:-1}
    restart: unless-stopped

  web:
    build:
      context: web
    restart: unless-stopped

  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
      - directus
      # - web
    volumes:
      - "./server/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped
