branch-defaults:
  main:
    environment: sinarmas-externala-env
environment-defaults:
  sinarmas-externala-env:
    branch: null
    repository: null
global:
  application_name: sinarmas-externalapps
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: ./.elasticbeanstalk/my-app.zip
