name: Push main to GitLab development

on:
  push:
    branches:
      - main

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab development
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Tambahkan remote GitLab
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.ugems.id/external-apps/x-rels-web.git

          # Push branch main GitHub ke branch development GitLab
          git push gitlab main:development
